version: '3.2'

services:
  kimby-grpc-offerings:
    build:
      dockerfile: Dockerfile
      context: ../../grpc-offerings
      args:
        NODE_AUTH_TOKEN: ${NODE_AUTH_TOKEN}
    environment:
      - PORT=10004
      - HOST=kimby-grpc-offerings
      - PROTO_PATH=./service.proto
      - INVENTORY_GRPC_URL=kimby-grpc-inventory
      - INVENTORY_GRPC_PORT=10005
      - ORDERS_GRPC_URL=kimby-grpc-orders
      - ORDERS_GRPC_PORT=10006
      - PAYMENTS_GRPC_URL=kimby-grpc-payments
      - PAYMENTS_GRPC_PORT=10007
      - MONGODB_URL=mongodb://root:example@kimby-mongo:27017/
    volumes:
      - /app/node_modules
      - ../../grpc-offerings:/app
    ports:
      - '10004:10004'
    restart: always
